name: Docker build and publish

on:
  workflow_dispatch:

jobs:
  build_amd64:
    name: Build and push Docker images
    strategy:
      matrix: 
        runner: [ubuntu-latest , [self-hosted, linux, ARM64]]
        platform: [linux/amd64, linux/arm64]

    runs-on: ${{ matrix.runner }}
    steps:
      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          platforms: ${{ matrix.platform }}
          push: true
          tags: ghcr.io/montejojorge/electrs-ui:latest