name: Docker build and publish

on:
  workflow_dispatch:

jobs:
  build_amd64:
    name: Build amd64
    runs-on: ubuntu-latest
    steps:
      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          push: false
          tags: ghcr.io/montejojorge/electrs-ui:latest
      - name: Set DOCKER_IMAGE_ID
        run: echo "DOCKER_IMAGE_ID=${{ steps.docker_build.outputs.digest }}" >> $GITHUB_ENV

  build_arm64:
    name: Build arm64
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64
          push: false
          tags: ghcr.io/montejojorge/electrs-ui:latest
      - name: Set DOCKER_IMAGE_ID
        run: echo "DOCKER_IMAGE_ID=${{ steps.docker_build.outputs.digest }}" >> $GITHUB_ENV

  push:
    needs: [build_amd64, build_arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/montejojorge/electrs-ui:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache